apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp.fullname" . }}-server
spec:
  selector:
    app: server
  ports:
    - port: {{ .Values.server.servicePort }}
      targetPort: {{ .Values.server.containerPort }}
      nodePort: {{ .Values.server.nodePort }}
  type: NodePort
