replicaCount: 1

image:
  pullPolicy: IfNotPresent

client:
  repository: dingus27/client
  tag: latest
  containerPort: 80
  servicePort: 8081
  nodePort: 30081

server:
  repository: dingus27/server
  tag: latest
  containerPort: 5000
  servicePort: 5001
  nodePort: 30050

postgres:
  repository: postgres
  tag: "13"
  user: postgres
  password: postgres
  db: flask_vue
  # For dev we use emptyDir. In production change to PVC + storageClass.
  persistence:
    enabled: false
