apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: flask-vue
type: Opaque
stringData:
  POSTGRES_PASSWORD: "postgres"   # change for real environments
  POSTGRES_USER: "postgres"
  POSTGRES_DB: "flask_vue"
